version: '3.4'

services:
  crawler:
    image: ${DOCKER_REGISTRY}crawler
    build:
      context: .
      dockerfile: Crawler/Dockerfile        
    depends_on:
          - db
  db:
    image: "microsoft/mssql-server-linux"
    environment:
        SA_PASSWORD: "password"
        ACCEPT_EULA: "Y"
