version: '3.4'

services:
  crawler:
    image: ${DOCKER_REGISTRY}crawler
    build:
      context: .
      dockerfile: Crawler/Dockerfile        
    depends_on:
          - dbcrawler
    environment:
      BETSERVICE_URI: "https://betservice:443/api"
    networks:
      - BetTrainer
  dbcrawler:
    image: "microsoft/mssql-server-linux"
    expose:
      - "1433"
    environment:
        SA_PASSWORD: "password12345PASSWORD"
        ACCEPT_EULA: "Y"
    networks:
      - BetTrainer

networks:
  BetTrainer:
    external: true