version: '3.4'

services:
  betservice:
    image: ${DOCKER_REGISTRY-}betservice
    build:
      context: .
      dockerfile: BetService/Dockerfile
    depends_on:
      - db
    networks:
      - BetTrainer
  db:
    image: "microsoft/mssql-server-linux"
    expose:
      - "1433"
    environment:
        SA_PASSWORD: "password12345PASSWORD"
        ACCEPT_EULA: "Y"
    networks:
      - BetTrainer

networks:
  BetTrainer:
    external: true